import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "All users",
  description: "Generated by create next app",
};

import getAllUsers from "@/lib/getAllUsers";

export default async function AllUsers() {
  const usersData: Promise<User[]> = getAllUsers();
  const users = await usersData;

  return (
    <>
      <Link href="/">Home</Link>
      <section>
        <p>All users</p>
        {users.map((user) => {
          return (
            <>
              <Link href={`/users/${user.id}`} key={user.id}>
                {user.name}
              </Link>
              <br></br>
            </>
          );
        })}
      </section>
    </>
  );
}
