import styles from "./page.module.css";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "About us",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className={styles.main}>
        <nav>about nav</nav>
        {children}
      </main>
    </>
  );
}
