// const data = {
//   products: [
//     {
//       name: 'EX DiSPLAY : MSI Pro 16',
//       slug: 'EX DiSPLAY : MSI Pro 16',
//       image: '/images/display1.jpg',
//       price: 100,
//       brand: 'Asus',
//       category: 'Computer and Laptops',
//       rating: 4',//       numReviews: 5,
//       stockStatus: 'Check Availability',
//       description: 'Asus display 2023',
//     },
//     {
//       name: 'SuperBook Pro',
//       slug: 'superbook-pro',
//       image: '/images/superbook.jpg',
//       price: 550,
//       brand: 'Apple',
//       category: 'Computer and Laptops',
//       rating: '4.5',
//       numReviews: 10,
//       stockStatus: 'In Stock',
//       description: 'SuperBook Pro 15-inch laptop',
//     },
//     {
//       name: 'Lenovo Flex 5',
//       slug: 'lenovo-flex-5',
//       image: '/images/lenovo-flex.jpg',
//       price: 800,
//       brand: 'Lenovo',
//       category: 'Computer and Laptops',
//       rating: '4.7',
//       numReviews: 15,
//       stockStatus: 'In Stock',
//       description: 'Lenovo Flex 5 2-in-1 laptop',
//     },
//     {
//       name: 'MSI Gaming Laptop',
//       slug: 'msi-gaming-laptop',
//       image: '/images/msi-laptop.jpg',
//       price: 120',
//       brand: 'MSI',
//       category: 'Computer and Laptops',
//       rating: '4.8',
//       numReviews: 20,
//       stockStatus: 'Check Availability',
//       description: 'Powerful gaming laptop by MSI',
//     },
//     {
//       name: 'Razer Blade 15',
//       slug: 'razer-blade-15',
//       image: '/images/razer-blade.jpg',
//       price: 180',
//       brand: 'Razer',
//       category: 'Computer and Laptops',
//       rating: '4.9',
//       numReviews: 25,
//       stockStatus: 'In Stock',
//       description: 'Razer Blade 15 gaming laptop',
//     },
//     {
//       name: 'Corsair Vengeance LPX',
//       slug: 'corsair-vengeance-lpx',
//       image: '/images/corsair-ram.jpg',
//       price: 90'
//       brand: 'Corsair',
//       category: 'Storage and Memory',
//       rating: '4.5',
//       numReviews: 8,
//       stockStatus: 'In Stock',
//       description: 'Corsair Vengeance LPX DDR4 RAM',
//     },
//     {
//       name: 'Samsung 1TB SSD',
//       slug: 'samsung-1tb-ssd',
//       image: '/images/samsung-ssd.jpg',
//       price: 200,
//       brand: 'Samsung',
//       category: 'Storage and Memory',
//       rating: '4.7',
//       numReviews: 12,
//       stockStatus: 'In Stock',
//       description: 'Samsung 1TB Solid State Drive',
//     },
//     {
//       name: 'WD Elements External HDD',
//       slug: 'wd-elements-external-hdd',
//       image: '/images/wd-hdd.jpg',
//       price: 80'
//       brand: 'Western Digital',
//       category: 'Storage and Memory',
//       rating: '4.6',
//       numReviews: 11,
//       stockStatus: 'Check Availability',
//       description: 'WD Elements 2TB External Hard Drive',
//     },
//   ],
// };

//---------------------------------------------------------------------

const data = {
  products: [
    {
      name: 'EX DiSPLAY : MSI Pro 16',
      slug: 'EX DiSPLAY : MSI Pro 16',
      image: '/images/sample.jpg',
      price: 100,
      brand: 'Asus',
      category: 'Computer and Laptops',
      rating: 4,
      numReviews: 5,
      stockStatus: 'Check Availability',
      description: 'Asus display 2023',
    },
    {
      name: 'SuperBook Pro',
      slug: 'superbook-pro',
      image: '/images/sample.jpg',
      price: 550,
      brand: 'Apple',
      category: 'Computer and Laptops',
      rating: 4.5,
      numReviews: 10,
      stockStatus: 'In Stock',
      description: 'SuperBook Pro 15-inch laptop',
    },
    {
      name: 'Lenovo Flex 5',
      slug: 'lenovo-flex-5',
      image: '/images/sample.jpg',
      price: 800,
      brand: 'Lenovo',
      category: 'Computer and Laptops',
      rating: 4.7,
      numReviews: 15,
      stockStatus: 'In Stock',
      description: 'Lenovo Flex 5 2-in-1 laptop',
    },
    {
      name: 'MSI Gaming Laptop',
      slug: 'msi-gaming-laptop',
      image: '/images/sample.jpg',
      price: 1200,
      brand: 'MSI',
      category: 'Computer and Laptops',
      rating: 4.8,
      numReviews: 20,
      stockStatus: 'Check Availability',
      description: 'Powerful gaming laptop by MSI',
    },
    {
      name: 'Razer Blade 15',
      slug: 'razer-blade-15',
      image: '/images/sample.jpg',
      price: 1800,
      brand: 'Razer',
      category: 'Computer and Laptops',
      rating: 4.9,
      numReviews: 25,
      stockStatus: 'In Stock',
      description: 'Razer Blade 15 gaming laptop',
    },
    {
      name: 'Corsair Vengeance LPX',
      slug: 'corsair-vengeance-lpx',
      image: '/images/sample.jpg',
      price: 90,
      brand: 'Corsair',
      category: 'Storage and Memory',
      rating: 4.5,
      numReviews: 8,
      stockStatus: 'In Stock',
      description: 'Corsair Vengeance LPX DDR4 RAM',
    },
    {
      name: 'Samsung 1TB SSD',
      slug: 'samsung-1tb-ssd',
      image: '/images/sample.jpg',
      price: 200,
      brand: 'Samsung',
      category: 'Storage and Memory',
      rating: 4.7,
      numReviews: 12,
      stockStatus: 'In Stock',
      description: 'Samsung 1TB Solid State Drive',
    },
    {
      name: 'WD Elements External HDD',
      slug: 'wd-elements-external-hdd',
      image: '/images/sample.jpg',
      price: 80,
      brand: 'Western Digital',
      category: 'Storage and Memory',
      rating: 4.6,
      numReviews: 11,
      stockStatus: 'Check Availability',
      description: 'WD Elements 2TB External Hard Drive',
    },
  ],
};
export default data;
