import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'EX DiSPLAY : MSI Pro 16',
      slug: 'EX DiSPLAY : MSI Pro 16',
      image: '/images/msiPro16Display.webp',
      price: 100,
      brand: 'Asus',
      category: 'Computer and Laptops',
      rating: 4,
      numReviews: 5,
      countInStock: 5,
      description: 'Asus display 2023',
    },
    {
      name: 'SuperBook Pro',
      slug: 'superbook-pro',
      image: '/images/superBookPro16.webp',
      price: 550,
      brand: 'Apple',
      category: 'Computer and Laptops',
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: 'SuperBook Pro 15-inch laptop',
    },
    {
      name: 'Lenovo Flex 5',
      slug: 'lenovo-flex-5',
      image: '/images/lenovoFlex5.webp',
      price: 800,
      brand: 'Lenovo',
      category: 'Computer and Laptops',
      rating: 4.7,
      numReviews: 15,
      countInStock: 5,
      description: 'Lenovo Flex 5 2-in-1 laptop',
    },
    {
      name: 'MSI Gaming Laptop',
      slug: 'msi-gaming-laptop',
      image: '/images/msiGame.webp',
      price: 1200,
      brand: 'MSI',
      category: 'Computer and Laptops',
      rating: 4.8,
      numReviews: 20,
      countInStock: 5,
      description: 'Powerful gaming laptop by MSI',
    },
    {
      name: 'Razer Blade 15',
      slug: 'razer-blade-15',
      image: '/images/razerBlade15.jpeg',
      price: 1800,
      brand: 'Razer',
      category: 'Computer and Laptops',
      rating: 4.9,
      numReviews: 25,
      countInStock: 5,
      description: 'Razer Blade 15 gaming laptop',
    },
    {
      name: 'Corsair Vengeance LPX',
      slug: 'corsair-vengeance-lpx',
      image: '/images/corsair.webp',
      price: 90,
      brand: 'Corsair',
      category: 'Storage and Memory',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
      description: 'Corsair Vengeance LPX DDR4 RAM',
    },
    {
      name: 'Samsung 1TB SSD',
      slug: 'samsung-1tb-ssd',
      image: '/images/samsung1tbssd.webp',
      price: 200,
      brand: 'Samsung',
      category: 'Storage and Memory',
      rating: 4.7,
      numReviews: 12,
      countInStock: 5,
      description: 'Samsung 1TB Solid State Drive',
    },
    {
      name: 'WD Elements External HDD',
      slug: 'wd-elements-external-hdd',
      image: '/images/wdElements.webp',
      price: 80,
      brand: 'Western Digital',
      category: 'Storage and Memory',
      rating: 4.6,
      numReviews: 11,
      countInStock: 5,
      description: 'WD Elements 2TB External Hard Drive',
    },
  ],
};

export default data;
